#ifndef ACTIONDEFINE_H
#define ACTIONDEFINE_H

#endif // ACTIONDEFINE_H

//主菜单--文件段
#define MENU_FILE_SECTION           0X100
#define MENU_FILE_NEWPROJ			MENU_FILE_SECTION + 1		//新建工程
#define MENU_FILE_OPENPROJ          MENU_FILE_SECTION + 2       //打开工程
#define MENU_FILE_RECOPENPROJ       MENU_FILE_SECTION + 3       //最近打开工程
#define MENU_FILE_RECOPENPROJ1       MENU_FILE_SECTION + 4       //工程1
#define MENU_FILE_RECOPENPROJ2       MENU_FILE_SECTION + 5       //工程2
#define MENU_FILE_RECOPENPROJ3       MENU_FILE_SECTION + 6       //工程3
#define MENU_FILE_CLOSEPROJ			MENU_FILE_SECTION + 7		//关闭工程
#define MENU_FILE_SAVEPROJ			MENU_FILE_SECTION + 8		//保存工程


